
CREATE TABLE IF NOT EXISTS `block_headers` ( 
   id UNSIGNED BIGINT PRIMARY KEY, 
	sig BLOB(32) NOT NULL, 
   height UNSIGNED BIGINT NULL, 
	version UNSIGNED SMALLINT DEFAULT 0, 
   gas_used UNSIGNED BIGINT DEFAULT 0,
	reward UNSIGNED BIGINT DEFAULT 0,
	total_tx UNSIGNED SMALLINT DEFAULT 0, 
   state_sig BLOB(32) NOT NULL, 
	tx_sig BLOB(32) NOT NULL, 
   parent_block_sig BLOB(32) NOT NULL, 
	ts UNSIGNED INTEGER DEFAULT 0
);
