
CREATE TABLE `block_headers` ( 
   id UNSIGNED INTEGER PRIMARY KEY, 
	sig BLOB(32) NOT NULL, 
   height UNSIGNED INTEGER NOT NULL, 
	version UNSIGNED SMALLINT DEFAULT 0, 
   gas_used UNSIGNED INTEGER DEFAULT 0,
	reward UNSIGNED INTEGER DEFAULT 0,
	total_tx UNSIGNED SMALLINT DEFAULT 0, 
   state_sig BLOB(32) NOT NULL, 
	tx_sig BLOB(32) NOT NULL, 
   parent_block_sig BLOB(32) NOT NULL, 
	ts UNSIGNED INTEGER DEFAULT 0
);
