
CREATE TABLE IF NOT EXISTS `transactions`(
   sig BLOB(32) PRIMARY KEY,
   block_id UNSIGNED BIGINT REFERENCES block_headers(id),
   seq UNSIGNED SMALLINT DEFAULT 0,
   type UNSIGNED TINYINT,
   nonce UNSIGNED INTEGER,
   sender BLOB,
   supplied_gas UNSIGNED BIGINT DEFAULT 0,
   gas_limit UNSIGNED BIGINT DEFAULT 0,
   value UNSIGNED BIGINT DEFAULT 0,
   receiver BLOB,
   proof BLOB,
   expiration UNSIGNED INTEGER,
   ts UNSIGNED INTEGER
);
